create table answer (id bigint not null auto_increment, person_id bigint, primary key (id)) engine=InnoDB;
create table diagnostic (id bigint not null auto_increment, classification varchar(255), final_note decimal(19,2), reply_submission_date datetime not null, answer_id bigint, person_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table item (id bigint not null, codigo_resposta bigint, description varchar(255), note_item decimal(19,2), resposta_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table question (id bigint not null, description varchar(255) not null, primary key (id)) engine=InnoDB;
alter table answer add constraint FK1ak7v8sevh6wf93tmc21nd47h foreign key (person_id) references person (id);
alter table diagnostic add constraint FK8e3pshfj5wfebdlx5mjswvix6 foreign key (answer_id) references answer (id);
alter table diagnostic add constraint FKgyo6bdscvt01nor7h18h5r4jw foreign key (person_id) references person (id);
alter table item add constraint FKlnn60xihm5k9iasp0oy91ugtm foreign key (resposta_id) references answer (id);
create table answer (id bigint not null auto_increment, person_id bigint, primary key (id)) engine=InnoDB;
create table diagnostic (id bigint not null auto_increment, classification varchar(255), final_note decimal(19,2), reply_submission_date datetime not null, answer_id bigint, person_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table item (id bigint not null, codigo_resposta bigint, description varchar(255), note_item decimal(19,2), resposta_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table question (id bigint not null, description varchar(255) not null, primary key (id)) engine=InnoDB;
alter table answer add constraint FK1ak7v8sevh6wf93tmc21nd47h foreign key (person_id) references person (id);
alter table diagnostic add constraint FK8e3pshfj5wfebdlx5mjswvix6 foreign key (answer_id) references answer (id);
alter table diagnostic add constraint FKgyo6bdscvt01nor7h18h5r4jw foreign key (person_id) references person (id);
alter table item add constraint FKlnn60xihm5k9iasp0oy91ugtm foreign key (resposta_id) references answer (id);
create table answer (id bigint not null auto_increment, person_id bigint, primary key (id)) engine=InnoDB;
create table diagnostic (id bigint not null auto_increment, classification varchar(255), final_note decimal(19,2), reply_submission_date datetime not null, answer_id bigint, person_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table item (id bigint not null, codigo_resposta bigint, description varchar(255), note_item decimal(19,2), resposta_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table question (id bigint not null, description varchar(255) not null, primary key (id)) engine=InnoDB;
alter table answer add constraint FK1ak7v8sevh6wf93tmc21nd47h foreign key (person_id) references person (id);
alter table diagnostic add constraint FK8e3pshfj5wfebdlx5mjswvix6 foreign key (answer_id) references answer (id);
alter table diagnostic add constraint FKgyo6bdscvt01nor7h18h5r4jw foreign key (person_id) references person (id);
alter table item add constraint FKlnn60xihm5k9iasp0oy91ugtm foreign key (resposta_id) references answer (id);
create table answer (id bigint not null auto_increment, person_id bigint, primary key (id)) engine=InnoDB;
create table diagnostic (id bigint not null auto_increment, classification varchar(255), final_note decimal(19,2), reply_submission_date datetime not null, answer_id bigint, person_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table item (id bigint not null, codigo_resposta bigint, description varchar(255), note_item decimal(19,2), resposta_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table question (id bigint not null, description varchar(255) not null, primary key (id)) engine=InnoDB;
alter table answer add constraint FK1ak7v8sevh6wf93tmc21nd47h foreign key (person_id) references person (id);
alter table diagnostic add constraint FK8e3pshfj5wfebdlx5mjswvix6 foreign key (answer_id) references answer (id);
alter table diagnostic add constraint FKgyo6bdscvt01nor7h18h5r4jw foreign key (person_id) references person (id);
alter table item add constraint FKlnn60xihm5k9iasp0oy91ugtm foreign key (resposta_id) references answer (id);
create table answer (id bigint not null auto_increment, person_id bigint, primary key (id)) engine=InnoDB;
create table diagnostic (id bigint not null auto_increment, classification varchar(255), final_note decimal(19,2), reply_submission_date datetime not null, answer_id bigint, person_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table item (id bigint not null, codigo_resposta bigint, description varchar(255), note_item decimal(19,2), resposta_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table question (id bigint not null, description varchar(255) not null, primary key (id)) engine=InnoDB;
alter table answer add constraint FK1ak7v8sevh6wf93tmc21nd47h foreign key (person_id) references person (id);
alter table diagnostic add constraint FK8e3pshfj5wfebdlx5mjswvix6 foreign key (answer_id) references answer (id);
alter table diagnostic add constraint FKgyo6bdscvt01nor7h18h5r4jw foreign key (person_id) references person (id);
alter table item add constraint FKlnn60xihm5k9iasp0oy91ugtm foreign key (resposta_id) references answer (id);
create table answer (id bigint not null auto_increment, person_id bigint, primary key (id)) engine=InnoDB;
create table diagnostic (id bigint not null auto_increment, classification varchar(255), final_note decimal(19,2), reply_submission_date datetime not null, answer_id bigint, person_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table item (id bigint not null, codigo_resposta bigint, description varchar(255), note_item decimal(19,2), resposta_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table question (id bigint not null, description varchar(255) not null, primary key (id)) engine=InnoDB;
alter table answer add constraint FK1ak7v8sevh6wf93tmc21nd47h foreign key (person_id) references person (id);
alter table diagnostic add constraint FK8e3pshfj5wfebdlx5mjswvix6 foreign key (answer_id) references answer (id);
alter table diagnostic add constraint FKgyo6bdscvt01nor7h18h5r4jw foreign key (person_id) references person (id);
alter table item add constraint FKlnn60xihm5k9iasp0oy91ugtm foreign key (resposta_id) references answer (id);
create table answer (id bigint not null auto_increment, person_id bigint, primary key (id)) engine=InnoDB;
create table diagnostic (id bigint not null auto_increment, classification varchar(255), final_note decimal(19,2), reply_submission_date datetime not null, answer_id bigint, person_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table item (id bigint not null, codigo_resposta bigint, description varchar(255), note_item decimal(19,2), resposta_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table question (id bigint not null, description varchar(255) not null, primary key (id)) engine=InnoDB;
alter table answer add constraint FK1ak7v8sevh6wf93tmc21nd47h foreign key (person_id) references person (id);
alter table diagnostic add constraint FK8e3pshfj5wfebdlx5mjswvix6 foreign key (answer_id) references answer (id);
alter table diagnostic add constraint FKgyo6bdscvt01nor7h18h5r4jw foreign key (person_id) references person (id);
alter table item add constraint FKlnn60xihm5k9iasp0oy91ugtm foreign key (resposta_id) references answer (id);
create table answer (id bigint not null auto_increment, person_id bigint, primary key (id)) engine=InnoDB;
create table diagnostic (id bigint not null auto_increment, classification varchar(255), final_note decimal(19,2), reply_submission_date datetime not null, answer_id bigint, person_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table item (id bigint not null, codigo_resposta bigint, description varchar(255), note_item decimal(19,2), resposta_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table question (id bigint not null, description varchar(255) not null, primary key (id)) engine=InnoDB;
alter table answer add constraint FK1ak7v8sevh6wf93tmc21nd47h foreign key (person_id) references person (id);
alter table diagnostic add constraint FK8e3pshfj5wfebdlx5mjswvix6 foreign key (answer_id) references answer (id);
alter table diagnostic add constraint FKgyo6bdscvt01nor7h18h5r4jw foreign key (person_id) references person (id);
alter table item add constraint FKlnn60xihm5k9iasp0oy91ugtm foreign key (resposta_id) references answer (id);
create table answer (id bigint not null auto_increment, person_id bigint, primary key (id)) engine=InnoDB;
create table diagnostic (id bigint not null auto_increment, classification varchar(255), final_note decimal(19,2), reply_submission_date datetime not null, answer_id bigint, person_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table item (id bigint not null, codigo_resposta bigint, description varchar(255), note_item decimal(19,2), resposta_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table question (id bigint not null, description varchar(255) not null, primary key (id)) engine=InnoDB;
alter table answer add constraint FK1ak7v8sevh6wf93tmc21nd47h foreign key (person_id) references person (id);
alter table diagnostic add constraint FK8e3pshfj5wfebdlx5mjswvix6 foreign key (answer_id) references answer (id);
alter table diagnostic add constraint FKgyo6bdscvt01nor7h18h5r4jw foreign key (person_id) references person (id);
alter table item add constraint FKlnn60xihm5k9iasp0oy91ugtm foreign key (resposta_id) references answer (id);
create table answer (id bigint not null auto_increment, person_id bigint, primary key (id)) engine=InnoDB;
create table diagnostic (id bigint not null auto_increment, classification varchar(255), final_note decimal(19,2), reply_submission_date datetime not null, answer_id bigint, person_id bigint, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table item (id bigint not null, codigo_resposta bigint, description varchar(255), note_item decimal(19,2), resposta_id bigint, primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table question (id bigint not null, description varchar(255) not null, primary key (id)) engine=InnoDB;
alter table answer add constraint FK1ak7v8sevh6wf93tmc21nd47h foreign key (person_id) references person (id);
alter table diagnostic add constraint FK8e3pshfj5wfebdlx5mjswvix6 foreign key (answer_id) references answer (id);
alter table diagnostic add constraint FKgyo6bdscvt01nor7h18h5r4jw foreign key (person_id) references person (id);
alter table item add constraint FKlnn60xihm5k9iasp0oy91ugtm foreign key (resposta_id) references answer (id);
