CREATE TABLE IF NOT EXISTS person (
	id BIGINT NOT NULL AUTO_INCREMENT,
	person_id BIGINT NULL,
    name VARCHAR(60) NOT NULL,
    email VARCHAR(60) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE person ADD CONSTRAINT fk_person_answer FOREIGN KEY (person_id) REFERENCES person (id);
