CREATE TABLE IF NOT EXISTS answer (
	id BIGINT NOT NULL AUTO_INCREMENT,
    id_person BIGINT NOT NULL,
    PRIMARY KEY(id) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE answer ADD CONSTRAINT fk_answer_person FOREIGN KEY (id_person) REFERENCES person (id);

CREATE TABLE IF NOT EXISTS item (
	id BIGINT NOT NULL,
    description VARCHAR(255) NULL,
    note_item DECIMAL(10,2) NULL,
    id_answer BIGINT NOT NULL,
    PRIMARY KEY(id) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE item ADD CONSTRAINT fk_item_answer FOREIGN KEY (id_answer) REFERENCES answer (id);